version: 0.2

phases:
  install:
    
    commands:
      - echo Installing dependencies
      # Add any additional commands to install dependencies here
      # Install AWS CLI
      - apt-get update && apt-get install -y awscli

  pre_build:
    commands:
      #- echo Configuring AWS CLI
      # Use existing AWS IAM user credentials
      

  build:
    commands:
      - echo Building WordPress app
      # Your remaining AWS CLI commands here
      - SECRET_ID="arn:aws:secretsmanager:ap-south-1:469553588024:secret:tf-db-ci-bgLKLX"
      - REGION="ap-south-1"
      # Fetch database credentials from AWS Secrets Manager
      - DB_CREDENTIALS=$(aws secretsmanager get-secret-value --secret-id $SECRET_ID --region $REGION --output json | jq -r '.SecretString')
      # Extract database connection details from the JSON response
      - DB_HOST=$(echo $DB_CREDENTIALS | jq -r '.DB_HOST')
      - DB_USERNAME=$(echo $DB_CREDENTIALS | jq -r '.DB_USER')
      - DB_PASSWORD=$(echo $DB_CREDENTIALS | jq -r '.DB_PASSWORD')
      - DB_NAME=$(echo $DB_CREDENTIALS | jq -r '.DB_NAME')
      - echo $DB_CREDENTIALS
      - echo $DB_HOST
      - echo $DB_NAME
      - echo $DB_USERNAME
      - echo $DB_PASSWORD
      # Add other fields as needed
      - echo Retrieving database credentials from AWS Secrets Manager
      # Update wp-config.php with the retrieved credentials
      # - sudo sed -i "s/define('DB_HOST', '.*');/define('DB_HOST', 'xxxxx');/" wp-config.php
      # - sudo sed -i "s/define('DB_USER', '.*');/define('DB_USER', '$DB_USERNAME');/" wp-config.php
      # - sudo sed -i "s/define('DB_PASSWORD', '.*');/define('DB_PASSWORD', '$DB_PASSWORD');/" wp-config.php
      # - sudo sed -i "s/define('DB_NAME', '.*');/define('DB_NAME', '$DB_NAME');/" wp-config.php
      - sudo sed -i "s/^.*DB_USER.*$/define('DB_USER', '$DB_USERNAME');/" wp-config.php
      - sudo sed -i "s/^.*DB_PASSWORD.*$/define('DB_PASSWORD', '$DB_PASSWORD');/" wp-config.php
      - sudo sed -i "s/^.*DB_NAME.*$/define('DB_NAME', '$DB_NAME');/" wp-config.php
      - sudo sed -i "s/^.*DB_HOST.*$/define('DB_HOST', '$DB_HOST');/" wp-config.php
  post_build:
    commands:
      
      # Add other sed commands for additional fields

artifacts:
  files:
    - "**/*"